# Generated by Django 5.2.8 on 2025-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
