# Generated by Django 5.2.8 on 2025-12-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
