# Generated by Django 5.2.8 on 2025-12-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chat',
            name='file_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
